2019-04-17 20:49:22,074 ERROR: Exception on /api/auth/token [POST] [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask_restplus\marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py", line 72, in post
    if not is_authorized_client(data['client_id'], data['client_secret']):
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py", line 25, in is_authorized_client
    u = User.objects(client_id=client_id).first()
AttributeError: type object 'User' has no attribute 'objects'
2019-04-17 20:50:06,070 ERROR: Exception on /api/auth/token [POST] [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "rastadev"
LINE 3: WHERE users.id = 'rastadev'
                         ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\flask_restplus\marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py", line 72, in post
    if not is_authorized_client(data['client_id'], data['client_secret']):
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py", line 25, in is_authorized_client
    u = User.query.get(client_id)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3275, in one
    ret = self.one_or_none()
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3244, in one_or_none
    ret = list(self)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\venv\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "rastadev"
LINE 3: WHERE users.id = 'rastadev'
                         ^

[SQL: SELECT users.id AS users_id, users.created_at AS users_created_at, users.username AS users_username, users.secret_hash AS users_secret_hash 
FROM users 
WHERE users.id = %(param_1)s]
[parameters: {'param_1': 'rastadev'}]
(Background on this error at: http://sqlalche.me/e/9h9h)
2019-04-17 20:51:07,468 ERROR: Unable to create token --> 'NAME' [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:96]
2019-04-17 20:52:11,180 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-17 20:53:03,420 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-17 20:53:23,294 WARNING: Unable to verify token [eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpc3MiOiJhcmR1aW5vX2FwaSIsImF1ZCI6ImFyZHVpbm9fbXF0dCIsImlhdCI6MTU1NTUyNzE4MywiZXhwIjoxNTU1NjEzNTgzLCJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InJhc3RhZGV2IiwiY3JlYXRlZF9hdCI6IjIwMTktMDQtMTdUMTg6NDg6NTMuNzQzOTQzIn19.iuRwk5Ia5oNj5xRsc3UXxERTPZUytW1mD5OhR4kx1iB18MtPbjOOLv5fkBknJiMgTihqSthXtmaqXHqHkE7eUCjfgcAo0ZHP7Kf6A7jTgE25YqctaFfuve_vLUCip61_-YzwXc7pSHsXlaNMPYKta5GbSYZgggGK07OBP0QMt6N4d16VxM9qcxMP_g4shQwvJDlJBZRHpbs0scLlUMPo8zSZ_C48j49x8VlW6B0aVYdZVDXuQwdII1maF_v5_oKdYp2HZH-1qHCacmOr9zyEi3R9EjPda4PY9q6G6V-F2TvVJPGn7LdIRypVbORvlggPIAq2y6vn-zsYys-tVZeW_oSwUz-bS5AuZQkNp8ul8sK9egb-83xVspV5atXhu1aPZitVhX8YLI8cI1dDoSkkLvbaiP30uCfpsc5kGDrWcCFf_SnZw8tJhXm33Cvf3RE9VbIOzT5tq3kd3uv9fHeBwNwnOk9DfHZukTfPeHY16KfDkCaTVMwTlTyPpOd5887fDg1zz_ufj3BT7H0r8-ZrBvCWrAKX6DPaNMQhNuuc-cUjOgzeCNvGS9Z-osAkhN-kt21Md0yXtg7PvkcXzehGt2cdh_GkJWF49W0uQpHDW6O4mOGDXg11sFmw7iC7WfHCB4reyYIDiJ-dCkVJ_fYr_ffeqZIebj2hNX7bY4Dye1E], reason : Invalid audience [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\__init__.py:47]
2019-04-18 19:14:04,407 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 19:16:03,756 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 19:16:12,118 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 19:17:04,115 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 19:23:01,927 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 19:26:03,826 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 19:27:37,050 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
2019-04-18 21:51:07,286 INFO: rastadev claim token [in C:\Users\averd\Projets\Sandbox\arduino_mqtt_led\app\api\endpoints\auth.py:88]
