2019-04-25 07:37:37,368 DEBUG: connack: 0 [in /daemon/app/__init__.py:56]
2019-04-25 07:37:37,368 INFO: connected [in /daemon/app/__init__.py:59]
